### PR TITLE
Added encryption and ACM certificates

### PR DESCRIPTION
**Pull request by jazzl0ver**
user is able to add encryption (DB and EFS) now
replaced IAM Server Certificates with ACM Certificates, which is a recommended way to add certificates to ELB
enable CopyTagsToSnapshot for DB instance

### CODE REVIEW

**Comment by jazzl0ver** [comment]
Hi. Any chances to get that merged?

**Comment by avattathil** [comment]
As mentioned in the Readme please send PR and or feature requests to the bitbucket repo. https://bitbucket.org/atlassian/atlassian-aws-deployment/src/c72c1496000de07d90ba2f98ad4309fe229ad19d/quickstarts/

**Comment by jazzl0ver** [comment]
I'm sorry, but i'm not familiar with yaml and bitbucket. All I wanted is just to incorporate my changes. Please, do that by yourself, if possible.

**Comment by avattathil** [comment]
Please maintain these changes in your fork or sync upstream as stated

**Pull request closed without merging**
