### PR TITLE
Enable choice of Amazon Aurora PostgreSQL as database

### PR DESCRIPTION
**Pull request by bpar476**
This update enables Amazon Aurora PostgreSQL as a database that can be deployed with Jira. It also comes with some minor bug fixes and style improvements.

### CODE REVIEW

**Comment by avattathil** [comment]
@bpar476 Should I hold off on this PR till the docs are ready?
@ddomingorh ^^

**Comment by bpar476** [comment]
Yep, lets hold the PR until next week.

**Comment by bpar476** [comment]
Also, I'm just investigating a bug that I've found 👀

**Comment by bpar476** [comment]
Bug has been fixed 👍

**Comment by bpar476** [comment]
We've experienced a delay in when we can support Aurora. Let's hold off on merging this PR until at least September 1. Will re-open when we confirm release time.

**Comment by bpar476** [comment]
Ready to rumble. Let's get this released first thing Monday the 2nd of September :D

**Comment by nanux** [comment]
We still need to hold off this PR merge until we will confirm Jira readiness.

**Comment by avattathil** [comment]
@nanux @bpar476 Are we ready on this PR?

**Comment by theghostwhoforks** [comment]
Hey @avattathil - Can we target to merge this on Monday evening your time (PST)? I'll get back to you with a confirmation on Monday

**Comment by theghostwhoforks** [comment]
Hey @avattathil - We are ready to merge this PR. This is good to go :)

**Comment by theghostwhoforks** [comment]
Updated the PR to remove conflicts with the base branch

**Pull request merged**
