### PR TITLE
Update EC2 instance types to current generation

### LINKED ISSUE #24: Update instance types
All instance types in the template are now considered [previous generation](https://aws.amazon.com/ec2/previous-generation/) and should be updated to the [current instance types](https://aws.amazon.com/ec2/pricing/on-demand/).

### PR DESCRIPTION
**Pull request by tlindsay42**
Resolves #24

### CODE REVIEW

**Comment by tlindsay42** [comment]
@avattathil, ready for review.

**Comment by tlindsay42** [comment]
Meh.  Decided not to use it since Atlassian obviously doesn't care about this project.

**Comment by Hilzerak** [comment]
but what else do you use for deployment? its mentioned in so many places in the docu...

**Comment by avattathil** [comment]
As mentioned in the Readme please send PR and or feature requests to the bitbucket repo. https://bitbucket.org/atlassian/atlassian-aws-deployment/src/c72c1496000de07d90ba2f98ad4309fe229ad19d/quickstarts/

**Pull request closed without merging**
