### PR TITLE
Update default Jira version to 8.20.1

### PR DESCRIPTION
**Pull request by nanux**
*Description of changes:*
Update default Jira version to 8.20.1

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nanux** [comment]
@tonynv, thank you for merging the PR. Unfortunately, I am not able to see the change in `main` branch and subsequently deployed into the official S3 bucket - the [template](https://aws-quickstart.s3.amazonaws.com/quickstart-atlassian-jira/templates/quickstart-jira-dc.template.yaml) still contains the old version of Jira. Is there something we need to do from our side?
Thank you

**Comment by tonynv** [comment]
@nanux looking this

**Comment by tonynv** [comment]
@nanux found a bug that cause issues with submodules.  I just pushed the fix.

**Comment by nanux** [comment]
> @nanux found a bug that cause issues with submodules. I just pushed the fix.

Thank you very much. Do we need to do something on our side?

**Comment by tonynv** [comment]
> > @nanux found a bug that cause issues with submodules. I just pushed the fix.
> 
> Thank you very much. Do we need to do something on our side?

No all good. We should be smooth on the next PR.

**Pull request merged**
